

patients = [
    {
        "id": "P-001",
        "name": "Messous Sara",
        "birth_date": "1984-03-12",
        "gender": "female",
        "blood_type": "A-",
        "status": "Stable",
        "symptoms": ["Mild headache", "Fatigue"],
        "medical_history": ["Asthma", "Appendectomy (2015)"],
        "medications": ["Ventolin (Albuterol)", "Multivitamins"],
        "allergies": ["Penicillin"],
        "vitals": {"bp": "118/75", "temp": 36.8, "hr": 72, "rr": 16, "spo2": 98},
        "labs": {"CBC": {"WBC": 6.2, "Hb": 14.1, "Platelets": 250}, "TSH": 2.0, "Electrolytes": {"Na": 138, "K": 4.2}},
        "imaging": {"Chest X-ray": "Clear"},
        "lifestyle": {"smoker": False, "alcohol": "Occasional", "exercise": "Moderate"},
        "family_history": ["Mother: Hypertension", "Father: Diabetes Type 2"],
        "notes": "Patient reports mild fatigue for 3 days, no respiratory distress.",
        "next_action": "Monitor symptoms; follow-up in 1 week if persists."
    },
    {
        "id": "P-002",
        "name": "Messous Yara",
        "birth_date": "1994-07-21",
        "gender": "Female",
        "blood_type": "O+",
        "status": "Observation",
        "symptoms": ["High fever", "Chills", "Nausea"],
        "medical_history": ["None"],
        "medications": ["Paracetamol", "IV Fluids"],
        "allergies": [],
        "vitals": {"bp": "130/85", "temp": 38.2, "hr": 104, "rr": 20, "spo2": 97},
        "labs": {"CBC": {"WBC": 14.5, "Hb": 13.2, "Platelets": 210}, "CRP": 45, "Electrolytes": {"Na": 136, "K": 3.8}},
        "imaging": {"Abdominal Ultrasound": "Normal"},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Low"},
        "family_history": ["None significant"],
        "notes": "Acute febrile illness, likely infectious etiology.",
        "next_action": "Repeat labs in 12 hours; consider blood cultures."
    },
    {
        "id": "P-003",
        "name": "Marcus Vane",
        "birth_date": "1956-11-09",
        "gender": "Male",
        "blood_type": "B+",
        "status": "Critical",
        "symptoms": ["Crushing chest pain", "Shortness of breath", "Diaphoresis"],
        "medical_history": ["Hypertension", "Type 2 Diabetes", "Smoker"],
        "medications": ["Nitroglycerin", "Aspirin", "Metformin"],
        "allergies": ["Latex"],
        "vitals": {"bp": "142/90", "temp": 36.5, "hr": 115, "rr": 28, "spo2": 89},
        "labs": {"Troponin I": 3.5, "CBC": {"WBC": 10.1, "Hb": 13.5, "Platelets": 230}, "HbA1c": 8.2},
        "imaging": {"ECG": "ST-elevation in leads II, III, aVF", "Chest X-ray": "Mild pulmonary congestion"},
        "lifestyle": {"smoker": "40 pack-years", "alcohol": "Occasional", "exercise": "Sedentary"},
        "family_history": ["Father: Myocardial infarction at 60"],
        "notes": "Acute inferior myocardial infarction; patient unstable.",
        "next_action": "Activate cath lab; monitor vitals continuously; start IV heparin."
    },
    {
        "id": "P-004",
        "name": "Messous Xiao",
        "birth_date": "1989-05-17",
        "gender": "Female",
        "blood_type": "AB-",
        "status": "Discharged",
        "symptoms": ["None (Resolved)"],
        "medical_history": ["C-Section (2020)"],
        "medications": ["Ibuprofen (PRN)"],
        "allergies": ["Sulfa"],
        "vitals": {"bp": "110/70", "temp": 36.6, "hr": 68, "rr": 14, "spo2": 99},
        "labs": {"CBC": {"WBC": 6.8, "Hb": 13.8, "Platelets": 245}, "CRP": 2.1},
        "imaging": {"Abdominal Ultrasound": "Normal post-op"},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Moderate"},
        "family_history": ["Mother: Healthy", "Father: Healthy"],
        "notes": "Post C-section recovery complete; no complications.",
        "next_action": "Routine follow-up in 6 weeks."
    },
    {
        "id": "P-005",
        "name": "Jordan Smith",
        "birth_date": "2011-09-30",
        "gender": "Male",
        "blood_type": "O-",
        "status": "Stable",
        "symptoms": ["Itchy skin", "Mild swelling"],
        "medical_history": ["Eczema"],
        "medications": ["Antihistamines", "Topical Corticosteroids"],
        "allergies": ["Peanuts", "Dairy"],
        "vitals": {"bp": "105/65", "temp": 37.1, "hr": 80, "rr": 18, "spo2": 99},
        "labs": {"CBC": {"WBC": 7.1, "Hb": 13.0, "Platelets": 260}, "IgE": 220},
        "imaging": {},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Active"},
        "family_history": ["Mother: Eczema", "Father: Asthma"],
        "notes": "Allergic reaction likely triggered by peanuts.",
        "next_action": "Avoid allergens; continue antihistamines; follow-up in 2 weeks."
    },
    {
        "id": "P-006",
        "name": "Elena Rodriguez",
        "birth_date": "1968-02-14",
        "gender": "Female",
        "blood_type": "A+",
        "status": "Observation",
        "symptoms": ["Abdominal pain", "Bloating"],
        "medical_history": ["Gallstones", "High Cholesterol"],
        "medications": ["Atorvastatin", "Omeprazole"],
        "allergies": ["Shellfish"],
        "vitals": {"bp": "135/88", "temp": 37.4, "hr": 88, "rr": 18, "spo2": 96},
        "labs": {"Liver Function": {"ALT": 55, "AST": 48}, "CBC": {"WBC": 8.5, "Hb": 13.5, "Platelets": 220}, "Lipids": {"LDL": 140, "HDL": 50}},
        "imaging": {"Abdominal Ultrasound": "Gallstones present"},
        "lifestyle": {"smoker": False, "alcohol": "Social", "exercise": "Low"},
        "family_history": ["Father: Gallstones", "Mother: Hyperlipidemia"],
        "notes": "Symptoms consistent with biliary colic.",
        "next_action": "Surgical consult for cholecystectomy; manage pain."
    },
    {
        "id": "P-007",
        "name": "Amara Okafor",
        "birth_date": "2001-12-05",
        "gender": "Female",
        "blood_type": "B-",
        "status": "Stable",
        "symptoms": ["Sore throat", "Runny nose"],
        "medical_history": ["Seasonal Allergies"],
        "medications": ["Loratadine"],
        "allergies": [],
        "vitals": {"bp": "115/72", "temp": 36.9, "hr": 70, "rr": 16, "spo2": 98},
        "labs": {"CBC": {"WBC": 7.2, "Hb": 13.8, "Platelets": 240}},
        "imaging": {},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Moderate"},
        "family_history": ["Mother: Allergic rhinitis"],
        "notes": "Likely viral upper respiratory infection.",
        "next_action": "Symptomatic management; follow-up if fever persists."
    },
    {
        "id": "P-008",
        "name": "David Miller",
        "birth_date": "1942-06-18",
        "gender": "Male",
        "blood_type": "O+",
        "status": "Critical",
        "symptoms": ["Confusion", "Slurred speech", "Weakness on left side"],
        "medical_history": ["Atrial Fibrillation", "Previous Stroke (2018)"],
        "medications": ["Warfarin", "Digoxin"],
        "allergies": ["Morphine"],
        "vitals": {"bp": "150/95", "temp": 36.2, "hr": 58, "rr": 12, "spo2": 91},
        "labs": {"INR": 3.1, "CBC": {"WBC": 9.0, "Hb": 12.5, "Platelets": 200}, "Electrolytes": {"Na": 140, "K": 4.0}},
        "imaging": {"CT Brain": "Acute ischemic stroke left MCA territory"},
        "lifestyle": {"smoker": "Past smoker", "alcohol": "None", "exercise": "Low"},
        "family_history": ["Father: Stroke at 70"],
        "notes": "Acute stroke on anticoagulation; high risk for bleeding.",
        "next_action": "Neurology consult; monitor vitals and INR; consider thrombolysis."
    },
    {
        "id": "P-009",
        "name": "Casey Tuan",
        "birth_date": "1978-01-05",
        "gender": "Non-binary",
        "blood_type": "A-",
        "status": "Stable",
        "symptoms": ["Wrist pain", "Swelling"],
        "medical_history": ["Carpal Tunnel Syndrome"],
        "medications": ["Naproxen"],
        "allergies": ["Pollen"],
        "vitals": {"bp": "122/80", "temp": 37.0, "hr": 76, "rr": 16, "spo2": 98},
        "labs": {"CBC": {"WBC": 6.5, "Hb": 14.0, "Platelets": 245}},
        "imaging": {"X-ray wrist": "No fracture; mild soft tissue swelling"},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Moderate"},
        "family_history": ["Mother: Arthritis"],
        "notes": "Inflammatory wrist pain; likely overuse.",
        "next_action": "Splint, NSAIDs, physiotherapy."
    },
    {
        "id": "P-010",
        "name": "Isabella Rossi",
        "birth_date": "1992-04-12",
        "gender": "Female",
        "blood_type": "AB+",
        "status": "Recovering",
        "symptoms": ["Surgical site soreness"],
        "medical_history": ["ACL Tear (Reconstructed)"],
        "medications": ["Tramadol", "Antibiotics"],
        "allergies": ["Aspirin"],
        "vitals": {"bp": "118/76", "temp": 36.7, "hr": 74, "rr": 16, "spo2": 99},
        "labs": {"CBC": {"WBC": 7.0, "Hb": 13.5, "Platelets": 250}, "CRP": 4},
        "imaging": {"Knee MRI": "Post-surgical changes; no complications"},
        "lifestyle": {"smoker": False, "alcohol": "Occasional", "exercise": "Moderate"},
        "family_history": ["Father: Healthy", "Mother: Osteoarthritis"],
        "notes": "Post-op recovery progressing well.",
        "next_action": "Continue physiotherapy; follow-up in 2 weeks."
    },
    {
        "id": "P-011",
        "name": "Omar Hassan",
        "birth_date": "1973-08-10",
        "gender": "Male",
        "blood_type": "B+",
        "status": "Stable",
        "symptoms": ["Lower back pain"],
        "medical_history": ["Herniated Disc"],
        "medications": ["Muscle Relaxants", "Ibuprofen"],
        "allergies": [],
        "vitals": {"bp": "128/82", "temp": 36.8, "hr": 78, "rr": 17, "spo2": 97},
        "labs": {"CBC": {"WBC": 6.8, "Hb": 14.0, "Platelets": 240}},
        "imaging": {"Lumbar MRI": "L4-L5 disc protrusion"},
        "lifestyle": {"smoker": False, "alcohol": "Occasional", "exercise": "Low"},
        "family_history": ["Father: Back pain"],
        "notes": "Chronic lower back pain exacerbation.",
        "next_action": "Continue meds; physiotherapy; consider pain specialist if persistent."
    },
    {
        "id": "P-012",
        "name": "Yuki Tanaka",
        "birth_date": "2007-11-02",
        "gender": "Female",
        "blood_type": "O-",
        "status": "Stable",
        "symptoms": ["Dizziness", "Pale skin"],
        "medical_history": ["Iron Deficiency Anemia"],
        "medications": ["Ferrous Sulfate (Iron)"],
        "allergies": ["Codeine"],
        "vitals": {"bp": "112/68", "temp": 37.2, "hr": 82, "rr": 18, "spo2": 98},
        "labs": {"CBC": {"WBC": 6.5, "Hb": 10.8, "Platelets": 250}, "Ferritin": 12},
        "imaging": {},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Moderate"},
        "family_history": ["Mother: Anemia"],
        "notes": "Symptoms consistent with iron deficiency.",
        "next_action": "Increase iron intake; dietary counseling; follow-up labs in 1 month."
    },
    {
        "id": "P-013",
        "name": "Liam O'Connor",
        "birth_date": "1985-09-22",
        "gender": "Male",
        "blood_type": "A+",
        "status": "Observation",
        "symptoms": ["Persistent cough", "Night sweats", "Fever"],
        "medical_history": ["Bronchitis (Recurring)"],
        "medications": ["Cough Suppressant", "Antipyretics"],
        "allergies": ["Dust Mites"],
        "vitals": {"bp": "132/84", "temp": 38.5, "hr": 98, "rr": 22, "spo2": 95},
        "labs": {"CBC": {"WBC": 11.5, "Hb": 14.0, "Platelets": 230}, "CRP": 38},
        "imaging": {"Chest X-ray": "Infiltrates in right lower lobe"},
        "lifestyle": {"smoker": False, "alcohol": "Social", "exercise": "Low"},
        "family_history": ["Father: COPD"],
        "notes": "Suspected pneumonia; needs monitoring.",
        "next_action": "Start antibiotics; repeat CXR in 48 hours."
    },
    {
        "id": "P-014",
        "name": "yuki Gupta",
        "birth_date": "1961-04-03",
        "gender": "Female",
        "blood_type": "B-",
        "status": "Stable",
        "symptoms": ["Joint stiffness", "Hand pain"],
        "medical_history": ["Rheumatoid Arthritis", "Osteoporosis"],
        "medications": ["Methotrexate", "Calcium Supplements"],
        "allergies": ["Iodine"],
        "vitals": {"bp": "125/78", "temp": 36.6, "hr": 72, "rr": 16, "spo2": 97},
        "labs": {"CBC": {"WBC": 6.8, "Hb": 13.5, "Platelets": 240}, "CRP": 12},
        "imaging": {"Hand X-ray": "Joint space narrowing, osteophytes"},
        "lifestyle": {"smoker": False, "alcohol": "None", "exercise": "Low"},
        "family_history": ["Mother: Arthritis"],
        "notes": "Chronic RA flare-up.",
        "next_action": "Adjust DMARDs; physiotherapy; monitor labs."
    },
]